spring:
  application:
    name: eureka-client1 # 为服务命名
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/ # 指定服务注册中心的地址
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: eureka-client1
    prefer-ip-address: true # 使用IP地址来定义注册中心的地址
server:
  port: 8090
